### ISSUE TITLE
Move to fsprojects/fantomas-for-vs?

### ISSUE THREAD

**Issue by dsyme** [fsprojects/fsharp-formatting-for-vs#22]
Hi @deviousasti 

Would you like to move this project into https://github.com/fsprojects to sit alongside fantomas?  

thanks

**Comment by deviousasti** [comment]
That would be a good idea. 
We do need this in a place where the bus factor is > 1.

**Comment by dsyme** [comment]
Cool. You should be able to transfer it straight in (github will automatically fix up links)

If not make me an admin and I can do it

Policies are here: https://github.com/fsprojects/fsprojects-admin

**Comment by deviousasti** [comment]
I've transferred it to fsprojects. Thank you!
Maintainer permissions for this repo probably needs to be set.

**Comment by dsyme** [comment]
Great! You have admin access

**Comment by dsyme** [comment]
I also renamed to "fantomas-for-vs", I hope that's OK, let me know if not
